### ISSUE TITLE
Security concerns

### ISSUE THREAD

**Issue by ninoM** [ftavares/gatsby-source-firebase_store#1]
If I'd like to host this in Netlify and would like to trigger a rebuild each time a data is added in firestore, how would I do that without committing in the firebase credentials json?

**Comment by ftavares** [comment]
Hey @ninoM .

To trigger a build everytime you add or change some info on firestore,  you can create a Firestore trigger, [tutorial](https://firebase.google.com/docs/functions/firestore-events), and call a Netlify build hook, (Go to _Build & deploy_ >  _Continuous Deployment_ and scroll to _Build hooks_).

You can add your credentials to Environment variables. 

On Netlify go to _Build & deploy_ >  _Continuous Deployment_ and scroll_Environment variables_, and add your credentials.

To use them on your project follow this [article](https://www.gatsbyjs.org/docs/environment-variables/). It's very well explained.

Thank you,
Fabio

**Comment by ninoM** [comment]
Awesome thank you for the speedy reply!
